### ISSUE TITLE
User can't pay to smartaddress with Blackbytes

### ISSUE THREAD

**Issue by pxrunes** [byteball/byteball#192]
I'm creating smart addresses with my chat bot to help exchanging blackbytes and bytes.

Creating Payment requests for (white) bytes works just fine. Creating them for Blackbytes results in an 
"not enough indivisible asset coins that fit the desired amount within the specified tolerances, make sure all your funds are confirmed" error. The wallet has enough funds of cause and i tryed it with diffent blackbyte amounts up to 200kbytes. 

What am i doing wrong?

![grafik](https://user-images.githubusercontent.com/30018462/28625131-9a7c00c2-721b-11e7-83ef-c5f8d694af66.png)

![grafik](https://user-images.githubusercontent.com/30018462/28625197-c4a7589c-721b-11e7-9822-9af748d83aa1.png)

**This is the definition of the smart wallet:**

`multi {"payments":[{"address":"42KSHDWTG3VY5WQT5MGVSGT5AIEWXZBU","amount":200000,"asset":"qO2JsiuDMh/j+pqJYZw3u82O71WjCDf0vTNvsnntr8o="}],"definitions":{"42KSHDWTG3VY5WQT5MGVSGT5AIEWXZBU":{"definition":["or",[["and",[["address","3XEJBQSULFXYVXARJ56AQE7K6O3UBKO5"],["seen",{"what":"output","asset":"base","amount":10000,"address":"ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"}]]],["and",[["address","ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"],["in data feed",[["I2ADHGP4HL6J37NQAD73J7E5SKFIXJOT"],"timestamp",">",1501077130551]],["not",["seen",{"what":"output","asset":"base","amount":10000,"address":"ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ"}]]]]]],"signers":{"r.0.0":{"address":"3XEJBQSULFXYVXARJ56AQE7K6O3UBKO5","member_signing_path":"r","device_address":"0ZKPSYDCRL6NESC4O35RVPVWSURZIDQ2B"},"r.1.0":{"address":"ZWTXO3GM2G4LUG7TBGLFCXK5RMYVPUQQ","member_signing_path":"r","device_address":"0GJAA6KRKVYAJN6UCTI2WXNDU2HG3PEDC"}}}}}`

**Comment by tonyofbyteball** [comment]
Did you try in 1.10.0?  Looks similar to bug that was fixed.

**Comment by pxrunes** [comment]
yes i did. The problem is still there. I'm creating the contract with the headless wallet and try to pay it from the 1.10.0 wallet. Didn't work :(
